version: '3.6'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_URL=127.0.0.1
      - POSTGRES_PASSWORD=1j6G7Ri3UIewT3B
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - net

  backend:
    depends_on:
      - db
    build: ./cadastro-usuarios-ws/
    restart: always
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - SECRET=fj23b7FH37hH30maSM37nf7fhM8f72fo6sfash
      - POSTGRES_URL=db
      - POSTGRES_PASSWORD=1j6G7Ri3UIewT3B
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      - net
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - backend
    build: ./cadastro-usuarios-web/
    restart: always
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:8080
    networks:
      - net
    ports:
      - 3000:3000
networks:
  net:
    driver: bridge