version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - 5432:5432

  backend:
    depends_on:
      - db
    build: ./cadastro-usuarios-ws/
    restart: always
    env_file:
      - ./cadastro-usuarios-ws/.env
    environment:
      POSTGRES_URL: db
    ports:
      - 8080:8080
    links:
        - db

  frontend:
    depends_on:
      - backend
    build: ./cadastro-usuarios-web/
    restart: always
    env_file:
      - ./cadastro-usuarios-web/.env
    environment:
      BASE_URL: backend
    ports:
      - 3000:3000
    links:
        - backend